export const SERVICE_ACCOUNT_CONNECTION_PROPS = [
  'AWS_REGION',
  'AWS_ROLE_ARN',
  'AWS_WEB_IDENTITY_TOKEN_FILE',
] as const;

export const CREDENTIALS_CONNECTION_PROPS = [
  'AWS_REGION',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
] as const;

export const OS_MODULE_OPTIONS_TOKEN = 'OS_MODULE_OPTIONS';
export const OS_CLIENT_TOKEN = 'OS_CLIENT';
